server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaofan797/microservicecloud-config.git #远端GitHub地址
          basedir: E:/localGit #本地git地址
          username: xiaofan797
          password: beckham797
#  rabbitmq:
#    host: 192.168.1.200
#    virtual-host: /virtual_hontek
#    username: xiaofan
#    password: hontek
eureka:
  client:
    service-url:
      #defaultZone: http://eureka:7001/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: config-server
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
