spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaofan797/microservicecloud-config.git #远端GitHub地址
          basedir: E:/localGit #本地git地址
          username: xiaofan797
          password: beckham797
  rabbitmq:
    host: localhost
    virtual-host: /virtual_hontek
    username: xiaofan
    password: hontek
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: config-server
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"